name = "toon_codec"
version = "1.0.0"
description = "TOON (Token-Oriented Object Notation) encoder/decoder - a compact, token-efficient format for LLM input"
licences = ["MIT"]
repository = { type = "github", user = "axelbellec", repo = "toon_codec" }
links = [
  { title = "TOON Specification", href = "https://github.com/johannschopplich/toon/blob/main/SPEC.md" },
]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
